### 1.
GET https://quay.io/v2/openshift/okd-content/manifests/4.5.0-0.okd-2020-08-12-020541-coredns HTTP/1.1

### 1.
GET https://quay.io/v2/openshift/okd-content/manifests/sha256:8cf7e06dd4095f2cd54e13fdb6fd313abbeb6e03d568f17956d97433623093c2 HTTP/1.1

### 1.
GET https://quay.io/v2/openshift/okd-content/manifests/sha256:8cf7e06dd4095f2cd54e13fdb6fd313abbeb6e03d568f17956d97433623093c2 HTTP/1.1


### 测试只获得blobs长度
HEAD https://quay.io/v2/openshift/okd-content/blobs/sha256:89eaaaf386250faa931481c7a091b8540c35739569482aaebe214e0c69999e7c HTTP/1.1

### 测试只获得blobs长度
# content-length 926491594
GET  https://quay.io/v2/openshift/okd-content/blobs/sha256:89eaaaf386250faa931481c7a091b8540c35739569482aaebe214e0c69999e7c HTTP/2.0
Range: bytes=926491504-92649152

###test 
GET http://127.0.0.1:3001/v2/ HTTP/1.1

###test 
GET http://127.0.0.1:3001/v2/openshift/okd-content/manifests/4.5.0-0.okd-2020-08-12-020541-coredns HTTP/1.1

###test 
HEAD http://127.0.0.1:3001/v2/openshift/okd-content/blobs/sha256:70a4a9f9d194035612c9bcad53b10e24875091230d7ff5f172b425a89f659b95 HTTP/1.1


### test nginx
GET http://reverse:8888/v2/openshift/okd-content/blobs/sha256:70a4a9f9d194035612c9bcad53b10e24875091230d7ff5f172b425a89f659b95 HTTP/1.1


###
GET http://127.0.0.1:8000/v2/openshift/okd-content/manifests/121 HTTP/1.1

###
GET https://quay.io/v2/openshift/okd-content/manifests/121 HTTP/1.1


###
GET http://127.0.0.1:8000/v2/openshift/okd-content/manifests/4.5.0-0.okd-2020-08-12-020541-coredns HTTP/1.1

###
GET http://127.0.0.1:8000/v2/library/node/manifests/12 HTTP/1.1
###
GET http://127.0.0.1:3000/v2/ HTTP/1.1

###
GET http://quay.io/v2 HTTP/1.1


###
GET  https://quay.io/v2/auth?service=quay.io&scope=repository:outline/shadowbox:pull HTTP/1.1

#####
GET https://quay.io/v2/outline/shadowbox/manifests/server-2020-09-28 HTTP/1.1
Accept: application/vnd.docker.distribution.manifest.v2+json
Authorization: 'Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6Ijg4NDkzY2EwNDk1ZmNkOWExYTgzMDAwZjFiOWI5NTRlOTM1ZmYxNTA4MjJiZTkzYTEwZmI4NjBmMjI5ZDIxNDEifQ.eyJhY2Nlc3MiOlt7InR5cGUiOiJyZXBvc2l0b3J5IiwibmFtZSI6Im91dGxpbmUvc2hhZG93Ym94IiwiYWN0aW9ucyI6WyJwdWxsIl19XSwiY29udGV4dCI6eyJjb20uYXBvc3RpbGxlLnJvb3RzIjp7Im91dGxpbmUvc2hhZG93Ym94IjoicXVheSJ9LCJjb20uYXBvc3RpbGxlLnJvb3QiOiJxdWF5In0sImF1ZCI6InF1YXkuaW8iLCJleHAiOjE2MDEyOTI1OTgsImlzcyI6InF1YXkiLCJpYXQiOjE2MDEyODg5OTgsIm5iZiI6MTYwMTI4ODk5OCwic3ViIjoiKGFub255bW91cykifQ.PRaLbPPitZNYwoivk3fiHbyUklgfw5SHKjstj_Vjb2bjz6jPTuF4_h9saw2MNFc_xCAqKkZbXZw0rdM871FHvhHbAphmKcw4Ysk00mC-CrWciU98gRJkN3oETGxut7GDdqyjyaHSgYlEYokZXAqKIlOEuZUNKBjM8wg6kOhohetW6eFJKy7Ci1HF9eGghMHtU3NCAUHVCKx5UUMDXZWLV0yhdYo2VCIbiars18LNcncF6x2BcqFKSrfmn6Y6J-x8_TyS_MdGfBS3ugFrwmBalIeLc7xNBN1OPreUBTLTvuSBc9_PIBLb_jQh0j2UWhMH7iS5P2L64JDLQRHU-VOh2Q'



######
PATCH http://127.0.0.1:8000/v2/abc/abc/blobs/uploads/aaa-aaa-aa-aa HTTP/1.1

aaaa
2222

###
HEAD http://127.0.0.1:8000/v2/abc/abc/blobs/sha256:70a4052d5bbcd7bc5c455ef23b2a02810495c61f936477b5453b144d43f18d05 HTTP/1.1