version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace:cached
      - vscode-extensions:/root/.vscode-server/extensions
    command: sleep infinity
    ports:
      - 3001:3001
      - 8000:8000
    networks:
      registry:
        aliases:
          - registry
  reverse:
    image: nginx
    ports:
      - 9999:8888
    volumes:
      - ./proxy.conf:/etc/nginx/conf.d/proxy.conf
    networks:
      registry:
        aliases:
          - reverse

networks:
  registry:

volumes:
  vscode-extensions:
    external: true
