version: "3"

services:
  nginx:
    image: nginx
    ports:
      - 6660:6660
      - 6661:6661
  proxy-quayio:
    container_name: registry_proxy-quayio
    image: shinhwagk/registry:latest
    volumes:
      - registry-cache:/var/lib/registry
    networks:
      registry:
        aliases:
          - quayio
  proxy-dockerio:
    container_name: registry_proxy-dockerio
    image: shinhwagk/registry:latest
    volumes:
      - registry-cache:/var/lib/registry
    networks:
      registry:
        aliases:
          - dockerio

networks:
  registry:

volumes:
  registry-cache:
    external: true
