name: build

on:
  push:
    branches: [master]

jobs:
  # sss:
  #   runs-on: ubuntu-latest
  #   services:
  #     nginx:
  #       image: nginx
  #       ports:
  #         - 80:80
  #   steps:
  #     - run: docker pull nginx
  #     - run: docker tag nginx docker.pkg.github.com/shinhwagk/registry/nginx:test
  #     - run: echo ${{ secrets.GITHUB_TOKEN }} | docker login https://docker.pkg.github.com -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
  #     - run: docker push docker.pkg.github.com/shinhwagk/registry/nginx:test
  #     - run: docker run -d --name nginx -p 8081:80 nginx
  #     - run: docker ps
  #     - run: docker-compose version
  #     - run: curl http://localhost:8081
  #     - run: exit 1
  # test:
  #   # needs: [sss]
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: actions/setup-node@v2-beta
  #     - run: npm i
  #     - run: npm run test
  #       env:
  #         storage: ./storage
  #         level: debug
  push:
    #     needs: [test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
      - run: |
          docker build -t shinhwagk/registry:$(cat package.json | jq -r .version) .
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker tag shinhwagk/registry:$(cat package.json | jq -r .version) shinhwagk/registry:latest
          docker push shinhwagk/registry:$(cat package.json | jq -r .version)
          docker push shinhwagk/registry:latest
