name: build

on:
  push:
    branches: [ master ]

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
    - run: npm i
    - run: npm run compile
    - run: docker build -t shinhwagk/registry:alpine .
    - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
    - run: docker push shinhwagk/registry