name: build

on:
  push:
    branches: [ master ]

jobs:
  ss1:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: echo aaa > aaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
    - run: ls -l ./
  sss:
    needs: [ss1]
    runs-on: ubuntu-latest
    services:
      nginx:
       image: nginx
       ports:
        - 80:80
    steps:
       - run: ls -l ./ && pwd
       - run: docker-compose version
       - run: curl http://localhost:${{ job.services.nginx.ports[80] }}
       - run: exit 1
  test:
    needs: [sss]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2-beta
    - run: npm i
    - run: sudo npm i -g ts-node
    - run: ts-node test/down.test.ts
    - run: |
        sha256sum=$(sha256sum storage/blobs | awk '{print $1}')
        sha236=89eaaaf386250faa931481c7a091b8540c35739569482aaebe214e0c69999e7c
        [ "${sha236}" == "${sha256sum}" ] || exit 1
  push:
    needs: [test]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2-beta
    - run: npm i
    - run: npm run compile
    - run: docker build -t shinhwagk/registry:alpine-$(cat package.json | jq -r .version) .
    - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
    - run: docker push shinhwagk/registry
