name: build

on:
  push:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2-beta
    - run: npm i
    - run: sudo npm i -g ts-node
    - run: ts-node test/down.test.ts
    - run: |
        sha256sum=$(storage/blobs)
        sha236=89eaaaf386250faa931481c7a091b8540c35739569482aaebe214e0c69999e7c
        [ "89eaaaf386250faa931481c7a091b8540c35739569482aaebe214e0c69999e7c" == "$sha256sum" ] || exit 1
  push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2-beta
    - run: npm i
    - run: npm run compile
    - run: docker build -t shinhwagk/registry:alpine-$(cat package.json | jq -r .version) .
    - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
    - run: docker push shinhwagk/registry