name: build

on:
  push:
    branches: [ master ]

jobs:
  sss:
    runs-on: ubuntu-latest
    services:
      nginx:
       image: nginx
       ports:
        - 80:80
    steps:
       - run: docker pull nginx
       - run: docker tag nginx docker.pkg.github.com/shinhwagk/library/nginx:1.0.0
       - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.GITHUBTOKEN }}
       - run: docker push docker.pkg.github.com/shinhwagk/library/nginx:1.0.0
       - run: docker run -d --name nginx  -p 8081:80 nginx
       - run: docker ps
       - run: docker-compose version
       - run: curl http://localhost:8081
       - run: exit 1
  test:
    needs: [sss]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2-beta
    - run: npm i
    - run: sudo npm i -g ts-node
    - run: ts-node test/down.test.ts
    - run: |
        sha256sum=$(sha256sum storage/blobs | awk '{print $1}')
        sha236=89eaaaf386250faa931481c7a091b8540c35739569482aaebe214e0c69999e7c
        [ "${sha236}" == "${sha256sum}" ] || exit 1
  push:
    needs: [test]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2-beta
    - run: npm i
    - run: npm run compile
    - run: docker build -t shinhwagk/registry:alpine-$(cat package.json | jq -r .version) .
    - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
    - run: docker push shinhwagk/registry
