name: build

on:
  push:
    branches: [nr]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
      - run: npm i
      - run: npm run compile
      - run: node dist/v21.js > test.log && sleep 5 &
      - run: |
          for i in `seq 1 10`; do
            for tag in `curl -s "https://quay.io/api/v1/repository/openshift/okd-content/tag/?limit=10&page=${i}&onlyActiveTags=true" | jq -r '.tags[].name'`; do
              docker pull quay.io/openshift/okd-content:${tag} && docker tag quay.io/openshift/okd-content:${tag} 127.0.0.1:8000/openshift/okd-content:${tag} && docker push 127.0.0.1:8000/openshift/okd-content:${tag} &
            done
            wait
          done
          wait
      - run: cat test.log
