name: build

on:
  push:
    branches: [nr]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
      - run: npm i
      - run: npm run compile-webpack
      - run: node dist/repository.min.js > test.log && sleep 5 &
      - run: |
          curl http://127.0.0.1:8000/v2/
          cat test/images | while read image; do
            docker pull -q quay.io/${image} > /dev/null && docker tag quay.io/${image} 127.0.0.1:8000/${image} && docker push 127.0.0.1:8000/${image} &
          done
          wait;
      - run: cat test.log
      - run: ls -l notes/test/openshift/okd-content/blobs | wc -l
