name: build

on:
  push:
    branches: [nr]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
      - run: npm i
      - run: |
          docker pull centos:8
          docker pull centos:7
      - run: npm run compile
      - run: node dist/v21.js > test.log && sleep 5 &
      - run: |
          docker tag centos:8 127.0.0.1:8000/test/centos:8
          docker tag centos:7 127.0.0.1:8000/test/centos:7
          docker push 127.0.0.1:8000/test/centos:8
          docker push 127.0.0.1:8000/test/centos:7
      - run: cat test.log