name: build

on:
  push:
    branches: [nr]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
      - run: npm i
      - run: npm run compile-webpack
      - run: node dist/repository.min.js > test.log && sleep 5 &
      - run: |
          for tag in `curl -s "https://quay.io/api/v1/repository/openshift/okd-content/tag/?limit=10&page=1&onlyActiveTags=true" | jq -r '.tags[].name'`; do
            docker pull -q quay.io/openshift/okd-content:${tag} > /dev/null && docker tag quay.io/openshift/okd-content:${tag} 127.0.0.1:8000/openshift/okd-content:${tag} && docker push 127.0.0.1:8000/openshift/okd-content:${tag} &
          done
          wait;
      - run: cat test.log
      - run: ls -l notes/test/quay.io/openshift/okd-content/blobs | wc -l
